import * as fs from "node:fs";
import * as path from "node:path";
import ignore, { type Ignore } from "ignore";
import type { BuiltinGroup, ResolvedConfig } from "../config/defaults.js";

export type ExclusionLayer = "gitignore" | `builtin:${BuiltinGroup}` | "user";

export interface ExclusionEntry {
  path: string;
  layer: ExclusionLayer;
}

const BUILTIN_PATTERNS: Record<BuiltinGroup, string[]> = {
  lockfiles: [
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "Gemfile.lock",
    "poetry.lock",
    "composer.lock",
    "Pipfile.lock",
    "go.sum",
  ],
  vendored: ["vendor/", "third_party/", "node_modules/", "bower_components/"],
  build_outputs: [
    "dist/",
    "build/",
    "out/",
    ".next/",
    ".nuxt/",
    "target/",
    "*.o",
    "*.a",
    "*.so",
    "*.dll",
    "*.exe",
  ],
  minified: ["*.min.js", "*.min.css"],
  binary_assets: [
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.bmp",
    "*.ico",
    "*.tiff",
    "*.svg",
    "*.pdf",
    "*.zip",
    "*.tar",
    "*.tar.gz",
    "*.tgz",
    "*.gz",
    "*.bz2",
    "*.xz",
    "*.7z",
    "*.wasm",
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.otf",
    "*.eot",
    "*.mp3",
    "*.mp4",
    "*.mov",
    "*.avi",
    "*.webm",
  ],
  generated_code: [
    "*.pb.go",
    "*_pb2.py",
    "*_pb.rb",
    "*.gen.ts",
    "*.gen.js",
    "*.generated.ts",
    "*.generated.js",
  ],
  // oversized handled separately (file size, not glob)
  oversized: [],
  config_files: [
    "lbvd.yaml",
    "lbvd.yml",
    ".lbvdrc",
    ".lbvd.yaml",
    ".lbvd.yml",
  ],
};

const OVERSIZED_BYTES = 2 * 1024 * 1024;
const GENERATED_HEAD_BYTES = 256;

export interface BuiltinMatcher {
  group: BuiltinGroup;
  ig: Ignore;
}

export function buildBuiltinMatchers(disabled: BuiltinGroup[]): BuiltinMatcher[] {
  const disabledSet = new Set(disabled);
  return (Object.keys(BUILTIN_PATTERNS) as BuiltinGroup[])
    .filter((g) => !disabledSet.has(g))
    .map((g) => ({ group: g, ig: ignore().add(BUILTIN_PATTERNS[g]) }));
}

export function buildUserMatcher(patterns: string[]): Ignore | null {
  if (patterns.length === 0) return null;
  return ignore().add(patterns);
}

export function buildGitignoreMatcher(repoRoot: string): Ignore | null {
  const giPath = path.join(repoRoot, ".gitignore");
  if (!fs.existsSync(giPath)) return null;
  const raw = fs.readFileSync(giPath, "utf8");
  return ignore().add(raw);
}

function isOversized(repoRoot: string, relPath: string): boolean {
  try {
    const full = path.join(repoRoot, relPath);
    const stat = fs.statSync(full);
    return stat.size > OVERSIZED_BYTES;
  } catch {
    return false;
  }
}

function looksGenerated(repoRoot: string, relPath: string): boolean {
  try {
    const full = path.join(repoRoot, relPath);
    const fd = fs.openSync(full, "r");
    try {
      const buf = Buffer.alloc(GENERATED_HEAD_BYTES);
      const n = fs.readSync(fd, buf, 0, GENERATED_HEAD_BYTES, 0);
      const head = buf.slice(0, n).toString("utf8");
      const firstTwoLines = head.split("\n").slice(0, 2).join("\n");
      return /Code generated by|Generated by/i.test(firstTwoLines);
    } finally {
      fs.closeSync(fd);
    }
  } catch {
    return false;
  }
}

export interface ClassifyOpts {
  repoRoot: string;
  config: ResolvedConfig;
}

export interface ClassifyResult {
  excluded: ExclusionLayer | null;
}

export function classify(relPath: string, opts: ClassifyOpts): ClassifyResult {
  const gitignoreMatcher = buildGitignoreMatcher(opts.repoRoot);
  if (gitignoreMatcher !== null && gitignoreMatcher.ignores(relPath)) {
    return { excluded: "gitignore" };
  }
  const builtinMatchers = buildBuiltinMatchers(opts.config.blacklist.disabled_builtins);
  for (const m of builtinMatchers) {
    if (m.ig.ignores(relPath)) {
      return { excluded: `builtin:${m.group}` };
    }
  }
  const disabled = new Set(opts.config.blacklist.disabled_builtins);
  if (!disabled.has("oversized") && isOversized(opts.repoRoot, relPath)) {
    return { excluded: "builtin:oversized" };
  }
  if (!disabled.has("generated_code") && looksGenerated(opts.repoRoot, relPath)) {
    return { excluded: "builtin:generated_code" };
  }
  const userMatcher = buildUserMatcher(opts.config.blacklist.patterns);
  if (userMatcher !== null && userMatcher.ignores(relPath)) {
    return { excluded: "user" };
  }
  return { excluded: null };
}
